# -*- coding: utf-8 -*-
"""goldcopy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Hhk4o_LF9iTIiI3MWlyA3MmDZtxVEyZ
"""

import numpy as np
import pandas as pd
from scipy.stats import beta
from scipy.interpolate import CubicSpline
from sklearn.preprocessing import MinMaxScaler
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF
import torch
import torch.nn.functional as F
from torch import Tensor
from torch.utils.data import IterableDataset
from typing import Optional, Tuple, Union
import warnings
from pathlib import Path
from tqdm import tqdm
from tabimpute.model.encoders import normalize_data
from tabimpute.prior.scm_prior import SCMPrior
import copy
from tabimpute.prior.mar_missing import MAR_missingness
from tabimpute.prior.mar_onesided_missing import MAR_onesided_missingness
from tabimpute.prior.mar_block_missing import MAR_block_missingness
from tabimpute.prior.mar_sequential_missing import UnifiedBandit
from tabimpute.diffusion.mar_diffusion_row10_30_col10_30_mar0_3_marblock0_3_marbandit0_4_epoch100_bs32_samples30k_lr1e_3 import (
    MARDiffusionModel,
    mar_diffusion_config,
)


# Helpers
def sample_log_uniform(low, high, size=1, base=np.e):
    return np.power(
        base,
        np.random.uniform(
            np.log(low) / np.log(base), np.log(high) / np.log(base), size
        ),
    )


def sample_exponential(scale, min_val, size=1):
    return min_val + np.round(np.random.exponential(scale=scale, size=size)).astype(int)


ACTIVATION_FUNCTIONS = {
    "identity": lambda x: x,
    "tanh": np.tanh,
    "leaky_relu": lambda x: np.maximum(0.01 * x, x),
    "elu": lambda x: np.where(x > 0, x, 0.5 * (np.exp(x) - 1)),
    "silu": lambda x: x / (1 + np.exp(-np.clip(x, -50, 50))),
    "sine": np.sin,
    "relu": lambda x: np.maximum(0, x),
    "relu6": lambda x: np.minimum(np.maximum(0, x), 6),
    "selu": lambda x: 1.0507
    * np.where(x > 0, x, 1.67326 * (np.exp(np.clip(x, -50, 50)) - 1)),
    "softplus": lambda x: np.log(1 + np.exp(np.clip(x, -50, 50))),
    "hardtanh": lambda x: np.maximum(-1, np.minimum(1, x)),
    "sign": np.sign,
    "rbf": lambda x: np.exp(-np.square(x)),
    "exp": lambda x: np.exp(np.clip(x, -10, 10)),
    "sqrt_abs": lambda x: np.sqrt(np.abs(x)),
    "indicator_abs_le_1": lambda x: np.where(np.abs(x) <= 1, 1, 0),
    "square": np.square,
    "absolute": np.abs,
    "relu_squared": lambda x: np.maximum(0, x) ** 2,
}


class RandomFourierFeatureFunction:
    def __init__(self, N=256):
        self.N, u = N, np.random.uniform(0.7, 3.0)
        self.b = np.random.uniform(0, 2 * np.pi, N)
        self.a = np.random.uniform(0, N, N)
        self.w = self.a ** (-np.exp(u))

    def __call__(self, x: np.ndarray) -> np.ndarray:
        z = np.random.randn(self.N)
        if x.ndim == 1:
            x = x[:, np.newaxis]
        phi_x = (self.w / np.linalg.norm(self.w)) * np.sin(self.a * x + self.b)
        return np.dot(phi_x, z)


class LatentFactorPrior:
    """Generates a complete data matrix using the Latent-Factor Families approach."""

    def __init__(self, config: dict):
        self.config = config
        self.distributions = ["Gaussian", "Laplace", "t_v", "Spike+Slab", "Dirichlet"]

    def _sample_latent_vectors(self, num_vectors: int, rank: int) -> np.ndarray:
        latent_matrix = np.zeros((num_vectors, rank))
        for i in range(num_vectors):
            choice = np.random.choice(self.distributions)
            if choice == "Gaussian":
                latent_matrix[i, :] = np.random.normal(
                    0, self.config.get("latent_gaussian_sigma", 1.0), size=rank
                )
            elif choice == "Laplace":
                latent_matrix[i, :] = np.random.laplace(
                    0, self.config.get("latent_laplace_b", 1.0), size=rank
                )
            elif choice == "t_v":
                df = np.random.randint(
                    self.config.get("latent_t_df_low", 2),
                    self.config.get("latent_t_df_high", 11),
                )
                latent_matrix[i, :] = np.random.standard_t(df, size=rank)
            elif choice == "Spike+Slab":
                is_spike = np.random.rand(rank) < self.config.get("latent_spike_p", 0.5)
                samples = np.random.normal(
                    0, self.config.get("latent_slab_sigma", 3.0), size=rank
                )
                samples[is_spike] = 0
                latent_matrix[i, :] = samples
            elif choice == "Dirichlet":
                alpha = np.full(rank, self.config.get("latent_dirichlet_alpha", 1.0))
                latent_matrix[i, :] = np.random.dirichlet(alpha) - (1 / rank)
        return latent_matrix

    def generate_complete_matrix(self) -> pd.DataFrame:
        n_rows = np.random.randint(self.config["num_rows_low"], self.config["num_rows_high"]+1)
        n_cols = np.random.randint(self.config["num_cols_low"], self.config["num_cols_high"]+1)
        rank = np.random.randint(
            self.config.get("latent_rank_low", 1),
            self.config.get("latent_rank_high", 11)+1,
        )
        U = self._sample_latent_vectors(n_rows, rank)
        V = self._sample_latent_vectors(n_cols, rank)
        Y = U @ V.T
        matrix = pd.DataFrame(Y, columns=[f"feature_{i}" for i in range(n_cols)])
        if np.random.rand() < self.config.get("apply_feature_warping_prob", 0.1):
            scaler = MinMaxScaler()
            for col in matrix.columns:
                col_data = scaler.fit_transform(matrix[[col]])
                a, b = np.random.rand() * 5 + 0.5, np.random.rand() * 5 + 0.5
                matrix[col] = scaler.inverse_transform(
                    beta.ppf(np.clip(col_data, 1e-10, 1 - 1e-10), a, b).reshape(-1, 1)
                ).flatten()
        if np.random.rand() < self.config["apply_quantization_prob"]:
            col_to_quantize = np.random.choice(matrix.columns)
            try:
                matrix[col_to_quantize] = pd.qcut(
                    matrix[col_to_quantize],
                    q=np.random.randint(2, 20),
                    labels=False,
                    duplicates="drop",
                )
            except (ValueError, IndexError):
                pass
        return matrix


class NonLinearFactorPrior(LatentFactorPrior):
    """Generates a complete data matrix using Non-linear Factor Models."""

    def __init__(self, config: dict):
        super().__init__(config)
        self.nonlinear_functions = [
            "sigmoid",
            "tanh",
            "relu_squared",
            # "spline",
            "gp_draw",
            "random_fourier",
        ]

    def _get_nonlinear_function(self, data_range: tuple[float, float]):
        choice = np.random.choice(self.nonlinear_functions)
        if choice == "sigmoid":
            return lambda x: 1 / (1 + np.exp(-np.clip(x, -50, 50)))
        elif choice == "tanh":
            return np.tanh
        elif choice == "relu_squared":
            return lambda x: np.maximum(0, x) ** 2
        elif choice == "spline":
            k = np.random.choice(self.config.get("spline_knot_k", [3, 5, 7]))
            x_knots = np.linspace(data_range[0], data_range[1], k)
            y_knots = np.random.randn(k)
            return CubicSpline(x_knots, y_knots, extrapolate=True)
        elif choice == "gp_draw":
            l = np.random.uniform(
                self.config.get("gp_length_scale_low", 0.3),
                self.config.get("gp_length_scale_high", 2.0),
            )
            gp = GaussianProcessRegressor(kernel=1.0 * RBF(length_scale=l))
            x_grid = np.linspace(data_range[0], data_range[1], 1000).reshape(-1, 1)
            y_grid = gp.sample_y(x_grid, 1, random_state=None).flatten()
            return lambda x: np.interp(x, x_grid.flatten(), y_grid)
        elif choice == "random_fourier":
            d_phi = np.random.randint(
                self.config.get("fourier_dim_low", 100),
                self.config.get("fourier_dim_high", 501),
            )
            rff = RandomFourierFeatureFunction(N=d_phi)
            return lambda x: rff(x.flatten()).reshape(x.shape)

    def generate_complete_matrix(self) -> pd.DataFrame:
        n_rows = int(
            sample_log_uniform(
                self.config["num_rows_low"], self.config["num_rows_high"]
            )[0]
        )
        n_cols = int(
            sample_log_uniform(
                self.config["num_cols_low"], self.config["num_cols_high"]
            )[0]
        )
        rank = np.random.randint(
            self.config.get("latent_rank_low", 1),
            self.config.get("latent_rank_high", 11),
        )
        U = self._sample_latent_vectors(n_rows, rank)
        V = self._sample_latent_vectors(n_cols, rank)
        dot_products = U @ V.T
        f = self._get_nonlinear_function(
            data_range=(dot_products.min(), dot_products.max())
        )
        Y = f(dot_products)
        matrix = pd.DataFrame(Y, columns=[f"feature_{i}" for i in range(n_cols)])
        if np.random.rand() < self.config["apply_feature_warping_prob"]:
            scaler = MinMaxScaler()
            for col in matrix.columns:
                col_data = scaler.fit_transform(matrix[[col]])
                a, b = np.random.rand() * 5 + 0.5, np.random.rand() * 5 + 0.5
                matrix[col] = scaler.inverse_transform(
                    beta.ppf(np.clip(col_data, 1e-10, 1 - 1e-10), a, b).reshape(-1, 1)
                ).flatten()
        if np.random.rand() < self.config["apply_quantization_prob"]:
            col_to_quantize = np.random.choice(matrix.columns)
            try:
                matrix[col_to_quantize] = pd.qcut(
                    matrix[col_to_quantize],
                    q=np.random.randint(2, 20),
                    labels=False,
                    duplicates="drop",
                )
            except (ValueError, IndexError):
                pass
        return matrix


class RobustPCAPrior(LatentFactorPrior):
    """Generates a complete data matrix using a Sparse + Low-Rank (Robust-PCA) approach."""

    def __init__(self, config: dict):
        super().__init__(config)

    def generate_complete_matrix(self) -> pd.DataFrame:
        L_df = super().generate_complete_matrix()
        L = L_df.values
        p_out = np.random.beta(
            self.config.get("rpca_beta_a", 2), self.config.get("rpca_beta_b", 30)
        )
        outlier_mask = np.random.rand(*L.shape) < p_out
        std_L = L.std()
        if std_L > 1e-6:
            gamma = 3 * std_L
            impulses = np.random.standard_cauchy(size=np.sum(outlier_mask)) * gamma
            S = np.zeros_like(L)
            S[outlier_mask] = impulses
            Y = L + S
        else:
            Y = L
        return pd.DataFrame(Y, columns=L_df.columns)


def _loraks_phase_encoding_observed_from_rng(
    ny: int, accel: int, acs_lines: int, rng: np.random.Generator
) -> np.ndarray:
    """1D phase mask: True where a phase-encoding line is observed (LORAKS convention)."""
    phase_observed = np.zeros(ny, dtype=bool)
    offset = int(rng.integers(0, accel))
    phase_observed[offset::accel] = True
    if acs_lines > 0:
        center = ny // 2
        half = acs_lines // 2
        lo = max(0, center - half)
        hi = min(ny, lo + acs_lines)
        phase_observed[lo:hi] = True
    return phase_observed


def loraks_cartesian_phase_encoding_observed(
    ny: int,
    accel: int,
    acs_lines: int,
    seed: int = 0,
) -> np.ndarray:
    """Boolean length-``ny``; True = k-space observed on that phase line.

    Matches the 1D slice underlying ``mcbench.workflows.loraks._cartesian_mask``
    for the same ``ny``, ``accel``, ``acs_lines``, and ``seed``.
    """
    if accel < 1:
        raise ValueError("accel must be >= 1.")
    if acs_lines < 0 or acs_lines > ny:
        raise ValueError("acs_lines must be in [0, ny].")
    rng = np.random.default_rng(seed)
    return _loraks_phase_encoding_observed_from_rng(ny, accel, acs_lines, rng)


def loraks_cartesian_kspace_observed_mask(
    shape: Tuple[int, int, int],
    accel: int,
    acs_lines: int,
    seed: int = 0,
) -> np.ndarray:
    """K-space observed mask, shape ``(nx, ny, ncoils)``, identical to LORAKS ``_cartesian_mask``."""
    nx, ny, ncoils = shape
    phase = loraks_cartesian_phase_encoding_observed(ny, accel, acs_lines, seed)
    return np.broadcast_to(phase[None, :, None], (nx, ny, ncoils)).copy()


def _loraks_build_patch_indices(
    shape_2d: Tuple[int, int], patch_shape: Tuple[int, int]
) -> Tuple[np.ndarray, Tuple[int, int]]:
    """Patch index grid for LORAKS ``S``-operator (same as ``mcbench.workflows.loraks``)."""
    nx, ny = shape_2d
    px, py = patch_shape
    if px < 2 or py < 2 or px > nx or py > ny:
        raise ValueError(f"Invalid patch shape {patch_shape} for shape {shape_2d}.")
    n_samples_x = nx - px + 1
    n_samples_y = ny - py + 1
    n_samples = n_samples_x * n_samples_y
    patch_entries = px * py
    indices = np.empty((patch_entries, n_samples), dtype=np.int64)
    col = 0
    for x0 in range(n_samples_x):
        for y0 in range(n_samples_y):
            patch = [
                (x0 + dx) * ny + (y0 + dy)
                for dx in range(px)
                for dy in range(py)
            ]
            indices[:, col] = np.asarray(patch, dtype=np.int64)
            col += 1
    return indices, (patch_entries, n_samples)


def _loraks_s_operator(
    kspace: np.ndarray,
    indices: np.ndarray,
    matrix_shape: Optional[Tuple[int, int]] = None,
) -> np.ndarray:
    """LORAKS ``S``-matrix construction (same as ``mcbench.workflows.loraks.loraks_s_operator``)."""
    data = np.asarray(kspace)
    if data.ndim != 3:
        raise ValueError("kspace must have shape (nx, ny, ncoils).")
    nx, ny, ncoils = data.shape
    patch_entries, n_samples = indices.shape if matrix_shape is None else matrix_shape
    if indices.shape != (patch_entries, n_samples):
        raise ValueError(
            f"indices shape {indices.shape} does not match matrix shape {matrix_shape}."
        )

    k_flat = np.transpose(data, (2, 0, 1)).reshape(ncoils, nx * ny)
    s_p = k_flat[:, indices.reshape(-1)].reshape(ncoils, patch_entries, n_samples)
    indices_rev = np.flip(indices, axis=0)
    s_m = k_flat[:, indices_rev.reshape(-1)].reshape(ncoils, patch_entries, n_samples)

    spm = s_p - s_m
    s_u = np.concatenate([spm.real, -spm.imag], axis=1)
    spp = s_p + s_m
    s_d = np.concatenate([spp.imag, spp.real], axis=1)
    s = np.concatenate([s_u, s_d], axis=2)
    return s.reshape(ncoils * 2 * patch_entries, 2 * n_samples).astype(np.float64, copy=False)


def loraks_lifted_finite_mask(
    shape: Tuple[int, int, int],
    patch_radius: int,
    accel: int,
    acs_lines: int,
    seed: int = 0,
) -> Tuple[np.ndarray, Tuple[int, int]]:
    """Where the lifted LORAKS ``S``-matrix is finite given Cartesian undersampling.

    Builds k-space with ``NaN`` on missing samples (as in ``generate_loraks_benchmark``),
    applies ``loraks_s_operator``, and returns ``numpy.isfinite(lifted)``.

    Returns
    -------
    finite
        Boolean array, shape ``(ncoils * 2 * patch_entries, 2 * n_samples)``.
    matrix_shape
        ``(patch_entries, n_samples)`` for use with LORAKS utilities.
    """
    if patch_radius < 1:
        raise ValueError("patch_radius must be >= 1.")
    nx, ny, _ = shape
    px = py = 2 * patch_radius + 1
    observed = loraks_cartesian_kspace_observed_mask(shape, accel, acs_lines, seed)
    nan_c = np.complex64(complex(np.nan, np.nan))
    one_c = np.complex64(1.0)
    kspace = np.where(observed, one_c, nan_c)
    indices, matrix_shape = _loraks_build_patch_indices((nx, ny), (px, py))
    lifted = _loraks_s_operator(kspace, indices, matrix_shape)
    return np.isfinite(lifted), matrix_shape


def save_loraks_lifted_mask_png(
    path: Union[str, Path],
    shape: Tuple[int, int, int] = (128, 128, 1),
    patch_radius: int = 3,
    accel: int = 4,
    acs_lines: int = 24,
    seed: int = 0,
    *,
    channel: str = "observed",
    max_display_side: int = 16000,
) -> Path:
    """Save a PNG of the **lifted** LORAKS ``S``-matrix finiteness mask.

    White means finite entries (patch fully in observed k-space when
    ``channel="observed"``); black means NaN in ``lifted_observed`` from
    ``loraks_lift``. For ``channel="missing"``, the colors are swapped.

    Large matrices are stride-subsampled **per axis** for the image only (wide
    S-matrices keep full row resolution).

    Requires matplotlib.
    """
    try:
        import matplotlib.pyplot as plt
    except ImportError as e:
        raise ImportError(
            "save_loraks_lifted_mask_png requires matplotlib. "
            "Install with: pip install matplotlib  (or tabimpute[benchmark])"
        ) from e

    path = Path(path).expanduser().resolve()
    finite, _ = loraks_lifted_finite_mask(shape, patch_radius, accel, acs_lines, seed)
    plane = finite.astype(np.float32)
    if channel == "missing":
        plane = 1.0 - plane
    elif channel != "observed":
        raise ValueError("channel must be 'observed' or 'missing'.")

    h_full, w_full = plane.shape
    step_h = (
        (h_full + max_display_side - 1) // max_display_side
        if h_full > max_display_side
        else 1
    )
    step_w = (
        (w_full + max_display_side - 1) // max_display_side
        if w_full > max_display_side
        else 1
    )
    if step_h > 1 or step_w > 1:
        plane = plane[::step_h, ::step_w]
    h_d, w_d = plane.shape

    nx, ny, ncoils = shape
    pr = patch_radius
    fig_w = min(48.0, max(10.0, w_d / 70.0))
    fig_h = min(24.0, max(4.0, h_d / 12.0))
    fig, ax = plt.subplots(figsize=(fig_w, fig_h))
    ax.imshow(plane, cmap="gray", interpolation="nearest", aspect="auto", vmin=0.0, vmax=1.0)
    title = (
        f"LORAKS lifted S-matrix ({channel})  full shape {h_full}×{w_full}  "
        f"nx={nx} ny={ny} ncoils={ncoils}  patch_radius={pr}  "
        f"accel={accel}  acs_lines={acs_lines}  seed={seed}"
    )
    if step_h > 1 or step_w > 1:
        title += f"  (display subsample row:{step_h} col:{step_w} → {h_d}×{w_d})"
    ax.set_title(title)
    ax.set_xlabel("2 * n_patch_samples (column index in lifted matrix)")
    ax.set_ylabel("ncoils * 2 * patch_entries (row index in lifted matrix)")
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return path


def save_loraks_cartesian_mask_png(
    path: Union[str, Path],
    shape: Tuple[int, int, int] = (128, 128, 1),
    accel: int = 4,
    acs_lines: int = 24,
    seed: int = 0,
    *,
    channel: str = "observed",
) -> Path:
    """Save a PNG visualization of the LORAKS Cartesian mask for visual inspection.

    The image is a single readout–phase plane (first coil). White pixels are
    observed k-space samples when ``channel="observed"``; black are missing.
    Use ``channel="missing"`` to invert (white = missing).

    Requires matplotlib (e.g. ``pip install matplotlib`` or ``tabimpute[benchmark]``).

    Parameters
    ----------
    path
        Output ``.png`` path.
    shape
        ``(nx, ny, ncoils)`` as in ``generate_loraks_benchmark``.
    accel, acs_lines, seed
        Same as the LORAKS benchmark generator.
    channel
        ``"observed"`` or ``"missing"``.
    """
    try:
        import matplotlib.pyplot as plt
    except ImportError as e:
        raise ImportError(
            "save_loraks_cartesian_mask_png requires matplotlib. "
            "Install with: pip install matplotlib  (or tabimpute[benchmark])"
        ) from e

    path = Path(path).expanduser().resolve()
    observed = loraks_cartesian_kspace_observed_mask(shape, accel, acs_lines, seed)
    plane = observed[:, :, 0].astype(np.float32)
    if channel == "missing":
        plane = 1.0 - plane
    elif channel != "observed":
        raise ValueError("channel must be 'observed' or 'missing'.")

    nx, ny, _ = shape
    fig, ax = plt.subplots(figsize=(max(6, ny / 32), max(6, nx / 32)))
    ax.imshow(plane, cmap="gray", interpolation="nearest", aspect="auto", vmin=0.0, vmax=1.0)
    ax.set_title(
        f"LORAKS Cartesian ({channel})  nx={nx} ny={ny}  accel={accel}  "
        f"acs_lines={acs_lines}  seed={seed}"
    )
    ax.set_xlabel("phase encoding (ny)")
    ax.set_ylabel("readout (nx)")
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return path


# Missingness Patterns
class BaseMissingness:
    def __init__(self, config: dict):
        self.config = config

    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        raise NotImplementedError


class MCARPattern(BaseMissingness):
    def _induce_missingness(self, X):
        X[torch.rand(*X.shape) < self.config.get("p_missing", 0.6)] = torch.nan
        return X
    
    def __str__(self):
        return "MCAR"


class MARPattern(BaseMissingness):
    def _induce_missingness(self, X):
        p, (_, n_cols) = self.config.get("p_missing", 0.6), X.shape
        num_predictors = np.random.randint(1, max(2, n_cols // 2))
        predictor_indices = np.random.choice(n_cols, num_predictors, replace=False)
        target_indices = np.setdiff1d(np.arange(n_cols), predictor_indices)
        predictors = X[:, predictor_indices]
        predictors[torch.isnan(predictors)] = 0
        log_odds = predictors @ torch.randn(len(predictor_indices))
        probs = torch.sigmoid(log_odds - torch.quantile(log_odds, 1 - p))
        for col_idx in target_indices:
            X[torch.rand(len(X)) < probs, col_idx] = torch.nan
        return X
    
    def __str__(self):
        return "MAR"


class MNARPattern(BaseMissingness):
    def _induce_missingness(self, X):
        p, (_, n_cols) = self.config.get("p_missing", 0.6), X.shape
        target_indices = np.random.choice(
            n_cols, np.random.randint(1, n_cols + 1), replace=False
        )
        for col_idx in target_indices:
            col_data = X[:, col_idx]
            log_odds = col_data * np.random.choice([-2, -1, 1, 2])
            if not torch.isnan(log_odds).all():
                beta_0 = -torch.quantile(log_odds[~torch.isnan(log_odds)], 1 - p)
                probs = torch.sigmoid(log_odds + beta_0)
                X[torch.rand(len(X)) < probs, col_idx] = torch.nan
        return X
    
    def __str__(self):
        return "MNAR"


class LoraksCartesianPattern(BaseMissingness):
    """Cartesian undersampling with a central ACS band, as in LORAKS MRI benchmarks.

    Mirrors ``_cartesian_mask`` in ``mcbench/workflows/loraks.py``: phase-encoding
    lines are sampled every ``accel``-th index with a random offset, and a
    contiguous block of lines around the center is fully observed (ACS).

    For tabular matrices, **columns** play the role of phase-encoding lines (the
    ``ny`` axis in k-space): each column is either entirely observed or entirely
    missing, matching the broadcast mask structure ``(nx, ny, ncoils)`` in the
    benchmark (readout and coil dimensions fully observed per line).

    Config keys (all optional): ``loraks_accel`` or ``accel`` (default 4),
    ``loraks_acs_lines`` or ``acs_lines`` (default 24), ``loraks_seed`` or
    ``seed`` (optional). When a seed is set, the undersampling offset matches
    ``numpy.random.default_rng(seed)`` as in ``generate_loraks_benchmark``; when
    omitted, a new unseeded generator is used each call (random offset per batch).
    """

    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        _, n_cols = X.shape
        accel = int(self.config.get("loraks_accel", self.config.get("accel", 4)))
        acs_lines = int(
            self.config.get("loraks_acs_lines", self.config.get("acs_lines", 24))
        )
        if accel < 1:
            raise ValueError("loraks_accel / accel must be >= 1.")
        if n_cols == 0:
            return X

        acs_lines = max(0, min(acs_lines, n_cols))

        seed = self.config.get("loraks_seed", self.config.get("seed", None))
        rng = (
            np.random.default_rng(int(seed))
            if seed is not None
            else np.random.default_rng()
        )
        phase_observed = _loraks_phase_encoding_observed_from_rng(
            n_cols, accel, acs_lines, rng
        )

        col_observed = torch.from_numpy(phase_observed).to(
            device=X.device, dtype=torch.bool
        )
        out = X.clone()
        out[:, ~col_observed] = torch.nan
        return out

    def __str__(self):
        return "LoraksCartesian"


class MNARRecSysPattern(BaseMissingness):
    def _induce_missingness(self, X):
        n_core, n_genres = self.config.get("n_core_items", 5), self.config.get(
            "n_genres", 4
        )
        n_users, n_items = X.shape
        if n_core >= n_items:
            n_core = n_items - 1
        item_genres = torch.randint(0, n_genres, (n_items - n_core,))
        user_genres = torch.randint(0, n_genres, (n_users,))
        mask = torch.full(X.shape, False)
        mask[:, :n_core] = True
        for i in range(n_users):
            matching_items = torch.where(item_genres == user_genres[i])[0] + n_core
            if len(matching_items) > 0:
                mask[i, matching_items] = True
        X[~mask] = torch.nan
        return X


class MNARPanelPattern(BaseMissingness):
    def _induce_missingness(self, X):
        n_users, n_timesteps = X.shape
        if n_timesteps <= 1:
            return X
        treatment_times = torch.randint(1, n_timesteps+1, (n_users,))
        for i in range(n_users):
            X[i, treatment_times[i] :] = torch.nan
        return X


class MNARSequentialPattern(BaseMissingness):
    def _induce_missingness(self, X):
        n_policies = self.config.get("n_policies", 2)
        n_users, n_cols = X.shape
        # if n_policies <= 0 or n_cols < n_policies or n_cols % n_policies != 0:
        #     return X
        n_timesteps = n_cols // n_policies
        mask = torch.ones(X.shape, dtype=torch.bool)
        for i in range(n_users):
            for t in range(n_timesteps):
                mask[i, t * n_policies + torch.randint(0, n_policies, (1,))] = True
        X[~mask] = torch.nan
        return X


class MNARPolarizationPattern(BaseMissingness):
    def _induce_missingness(self, X):
        threshold = self.config.get("threshold_quantile", 0.25)
        for j in range(X.shape[1]):
            col_data = X[:, j]
            if len(torch.unique(col_data[~torch.isnan(col_data)])) < 2:
                continue
            low = torch.quantile(col_data[~torch.isnan(col_data)], threshold)
            high = torch.quantile(col_data[~torch.isnan(col_data)], 1 - threshold)
            if low != high:
                X[(col_data > low) & (col_data < high), j] = torch.nan
        return X


class MNARSoftPolarizationPattern(BaseMissingness):
    """Induces missingness using a soft polarization pattern."""

    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        alpha = self.config.get("soft_polarization_alpha", np.random.uniform(1.1, 5.0))
        epsilon = self.config.get(
            "soft_polarization_epsilon", np.random.uniform(0.0, 0.1)
        )

        for j in range(X.shape[1]):
            col_data = X[:, j]
            valid_data = col_data[~torch.isnan(col_data)]
            if len(torch.unique(valid_data)) < 2:
                continue

            mu = torch.median(valid_data)
            deviation = torch.abs(col_data - mu) ** alpha
            max_deviation = torch.max(deviation[~torch.isnan(deviation)])

            if max_deviation < 1e-6:
                continue

            normalized_deviation = deviation / max_deviation
            p_obs = epsilon + (1 - 2 * epsilon) * normalized_deviation
            is_missing = torch.rand_like(p_obs) > p_obs
            col_data[is_missing] = torch.nan
            X[:, j] = col_data
        return X


class MNARLatentFactorPattern(BaseMissingness):
    """
    Induces missingness where the probability is determined by a low-rank
    dot-product of latent factors for rows and columns.
    p_ij = sigmoid(u_i^T v_j + b_i + c_j)
    """

    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        n_rows, n_cols = X.shape
        rank = np.random.randint(
            self.config.get("latent_rank_low", 1),
            self.config.get("latent_rank_high", 11),
        )

        # Sample latent factors and biases
        U = torch.randn(n_rows, rank)
        V = torch.randn(n_cols, rank)
        b = torch.randn(n_rows, 1)
        c = torch.randn(1, n_cols)

        # Calculate observation probabilities via sigmoid
        logits = U @ V.T + b + c
        p_obs = torch.sigmoid(logits)

        # Induce missingness
        mask = torch.rand_like(p_obs) > p_obs
        X[mask] = torch.nan
        return X


class MNARPositivityViolationPattern(BaseMissingness):
    """
    Induces missingness by zeroing-out entire blocks of rows and columns,
    """

    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        n_rows, n_cols = X.shape

        # Determine the size of the block to make missing
        row_block_size = int(n_rows * np.random.uniform(0.1, 0.4))
        col_block_size = int(n_cols * np.random.uniform(0.1, 0.4))

        # Choose a random starting point for the block
        row_start = np.random.randint(0, n_rows - row_block_size + 1)
        col_start = np.random.randint(0, n_cols - col_block_size + 1)

        # Define the block indices
        row_indices = slice(row_start, row_start + row_block_size)
        col_indices = slice(col_start, col_start + col_block_size)

        X[row_indices, col_indices] = torch.nan
        return X


class MNARUserCascadePattern(BaseMissingness):
    """
    Induces missingness based on a user cascade model, where observing one
    item increases the probability of observing related items (of the same genre).
    """

    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        n_rows, n_cols = X.shape
        n_genres = self.config.get("cascade_n_genres", 5)
        delta = self.config.get("cascade_delta", 1.5)  # bump factor

        # Assign a random genre to each column (item)
        item_genres = torch.randint(0, n_genres, (n_cols,))

        rank = np.random.randint(
            self.config.get("latent_rank_low", 1),
            self.config.get("latent_rank_high", 11),
        )
        U = torch.randn(n_rows, rank)
        V = torch.randn(n_cols, rank)
        base_logits = U @ V.T

        final_mask = torch.zeros_like(X, dtype=torch.bool)

        for i in range(n_rows):
            p_initial_row = torch.sigmoid(base_logits[i, :])
            d_initial_row = torch.rand_like(p_initial_row) < p_initial_row

            updated_logits_row = base_logits[i, :].clone()
            observed_indices = torch.where(d_initial_row)[0]
            for j in observed_indices:
                genre_j = item_genres[j]
                related_indices = torch.where(item_genres == genre_j)[0]
                updated_logits_row[related_indices] += delta

            p_final_row = torch.sigmoid(updated_logits_row)
            final_mask[i, :] = torch.rand_like(p_final_row) < p_final_row

        X[~final_mask] = torch.nan
        return X


class MNARClusterLevelPattern(BaseMissingness):
    """
    Induces missingness based on cluster-level random effects. Rows and columns
    are assigned to clusters, and each cluster has an offset that affects the
    observation probability of all its members.
    """

    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        n_rows, n_cols = X.shape

        num_row_clusters = self.config.get("cluster_level_n_row_clusters", 5)
        num_col_clusters = self.config.get("cluster_level_n_col_clusters", 5)
        tau_r_std = self.config.get("cluster_level_tau_r_std", 1.0)
        tau_c_std = self.config.get("cluster_level_tau_c_std", 1.0)
        epsilon_std = self.config.get("cluster_level_epsilon_std", 1.0)

        row_assignments = torch.randint(0, num_row_clusters, (n_rows,))
        col_assignments = torch.randint(0, num_col_clusters, (n_cols,))

        g_k = torch.randn(num_row_clusters) * tau_r_std
        h_l = torch.randn(num_col_clusters) * tau_c_std

        g_expanded = g_k[row_assignments].unsqueeze(1)
        h_expanded = h_l[col_assignments].unsqueeze(0)

        epsilon_noise = torch.randn(n_rows, n_cols) * epsilon_std

        logits = g_expanded + h_expanded + epsilon_noise
        p_obs = torch.sigmoid(logits)

        mask = torch.rand_like(p_obs) > p_obs
        X[mask] = torch.nan
        return X


class MNARSpatialBlockPattern(BaseMissingness):
    """
    Induces missingness by setting contiguous rectangular blocks to NaN,
    """

    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        n_rows, n_cols = X.shape
        n_blocks = self.config.get("spatial_block_n_blocks", 3)

        # p for geometric distribution of block size
        p_geom = self.config.get("spatial_block_p_geom", 0.1)

        for _ in range(n_blocks):
            # Sample block height and width
            height = min(np.random.geometric(p=p_geom), n_rows)
            width = min(np.random.geometric(p=p_geom), n_cols)

            row_start = np.random.randint(0, n_rows - height + 1)
            col_start = np.random.randint(0, n_cols - width + 1)

            X[row_start : row_start + height, col_start : col_start + width] = torch.nan

        return X


class MNARCensoringPattern(BaseMissingness):
    """
    Induces missingness by censoring values that are above or below a certain
    detection threshold
    """

    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        censor_quantile = self.config.get("censor_quantile", 0.1)

        for j in range(X.shape[1]):
            col_data = X[:, j]
            valid_data = col_data[~torch.isnan(col_data)]
            if len(torch.unique(valid_data)) < 2:
                continue

            # Randomly choose left or right censoring
            if np.random.rand() < 0.5:  # Left-censoring
                cutoff = torch.quantile(valid_data, censor_quantile)
                col_data[col_data < cutoff] = torch.nan
            else:  # Right-censoring
                cutoff = torch.quantile(valid_data, 1 - censor_quantile)
                col_data[col_data > cutoff] = torch.nan
            X[:, j] = col_data
        return X


class MNARTwoPhaseSubsetPattern(BaseMissingness):
    """
    Induces missingness based on a two-phase survey design. A subset of
    "expensive" columns are missing for rows based on their values in
    "cheap" (always observed) columns.
    """

    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        n_rows, n_cols = X.shape
        if n_cols < 2:
            return X

        frac = self.config.get("two_phase_cheap_fraction", 0.5)
        n_cheap = max(1, int(n_cols * frac))
        col_indices = np.random.permutation(n_cols)
        cheap_cols, expensive_cols = col_indices[:n_cheap], col_indices[n_cheap:]

        X_cheap = X[:, cheap_cols]
        weights = torch.randn(n_cheap)
        scores = X_cheap @ weights
        scores = (scores - scores.mean()) / (scores.std() + 1e-6)  # Normalize

        alpha = self.config.get("two_phase_alpha", 0)
        beta = self.config.get("two_phase_beta", 2.0)
        logits = alpha + beta * scores
        p_obs = torch.sigmoid(logits)

        is_missing = torch.rand(n_rows) > p_obs
        X[is_missing, :] = X[is_missing, :].index_fill(
            1, torch.tensor(expensive_cols), torch.nan
        )

        return X


class MNARSkipLogicPattern(BaseMissingness):
    """
    Induces missingness based on survey skip-logic, creating deterministic
    nested missingness patterns. Follow-up questions are missing if a
    "gate" question is answered a certain way.
    """

    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        _, n_cols = X.shape
        if n_cols < 2:
            return X

        p_noise = self.config.get("skip_logic_p_noise", 0.95)

        # Select a gate column and dependent columns
        gate_col = np.random.randint(0, n_cols)
        dependent_cols = [j for j in range(n_cols) if j != gate_col]

        # Binarize the gate column to create the skip condition
        gate_condition_met = X[:, gate_col] > torch.median(X[:, gate_col])

        rows_to_mask = ~gate_condition_met
        X[rows_to_mask, :] = X[rows_to_mask, :].index_fill(
            1, torch.tensor(dependent_cols), torch.nan
        )

        rows_passed = torch.where(gate_condition_met)[0]
        if len(rows_passed) > 0:
            rand_mask = torch.rand(len(rows_passed), len(dependent_cols)) > p_noise
            X[rows_passed.unsqueeze(1), torch.tensor(dependent_cols).unsqueeze(0)][
                rand_mask
            ] = torch.nan

        return X


class MNARColdStartPattern(BaseMissingness):
    """
    Induces missingness to simulate a cold-start or late-entry scenario, where
    some rows (users) have no data before a random entry time. The columns
    are treated as a time dimension.
    """

    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        n_rows, n_cols = X.shape
        if n_cols <= 1:
            return X

        frac = self.config.get("cold_start_fraction", 0.3)
        gamma = self.config.get("cold_start_gamma", 0.1)

        n_new_rows = int(n_rows * frac)
        new_row_indices = np.random.choice(n_rows, n_new_rows, replace=False)

        for i in new_row_indices:
            t0 = np.random.randint(1, n_cols)

            X[i, :t0] = torch.nan

            for t in range(t0, n_cols):
                p_obs = 1 - torch.exp(
                    -torch.tensor(gamma * (t - t0), dtype=torch.float32)
                )
                if torch.rand(1) > p_obs:
                    X[i, t] = torch.nan
        return X


def create_train_test_sets(
    X: torch.Tensor, X_full: torch.Tensor
) -> tuple[torch.Tensor, ...]:
    """
    Create train and test sets from a matrix with missing values.

    Args:
        X: Tensor of shape (n_rows, n_cols) with missing values.
        X_full: Tensor of shape (n_rows, n_cols) with complete values.

    Returns:
        train_X: Tensor of shape (n_rows, n_cols) with observed values.
        train_y: Tensor of shape (n_rows, n_cols) with observed values.
        test_X: Tensor of shape (n_rows, n_cols) with missing values.
        test_y: Tensor of shape (n_rows, n_cols) with missing values.
    """
    missing_indices, non_missing_indices = torch.where(torch.isnan(X)), torch.where(
        ~torch.isnan(X)
    )
    train_X_list, test_X_list, train_y_list, test_y_list = [], [], [], []
    for i, j in zip(non_missing_indices[0], non_missing_indices[1]):
        # row = torch.cat((X[i, :j], X[i, j + 1 :]))
        # col = torch.cat((X[:i, j], X[i + 1 :, j]))
        row = X[i, :]
        col = X[:, j]
        train_X_list.append(
            torch.cat((torch.tensor([i, j], device=X.device), row, col))
        )
        train_y_list.append(X_full[i, j])
    for i, j in zip(missing_indices[0], missing_indices[1]):
        # row = torch.cat((X[i, :j], X[i, j + 1 :]))
        # col = torch.cat((X[:i, j], X[i + 1 :, j]))
        row = X[i, :]
        col = X[:, j]
        test_X_list.append(torch.cat((torch.tensor([i, j], device=X.device), row, col)))
        test_y_list.append(X_full[i, j])
    train_X = (
        torch.stack(train_X_list)
        if train_X_list
        else torch.empty(
            0, X.shape[0] + X.shape[1] + 2
        )  # +2 for the row and column indices
    )
    train_y = torch.stack(train_y_list) if train_y_list else torch.empty(0)
    test_X = (
        torch.stack(test_X_list)
        if test_X_list
        else torch.empty(
            0, X.shape[0] + X.shape[1] + 2
        )  # +2 for the row and column indices
    )
    test_y = torch.stack(test_y_list) if test_y_list else torch.empty(0)

    # Clean up memory
    del train_X_list, train_y_list, test_X_list, test_y_list

    # Clear cache
    torch.cuda.empty_cache()

    return train_X, train_y, test_X, test_y


class SCMPriorTabICL:
    def __init__(self, config: dict):
        # Map the config to the SCMPrior config

        self.scm = SCMPrior(
            min_features=config["num_cols_low"],
            max_features=config["num_cols_high"],
            min_seq_len=config["num_rows_low"],
            max_seq_len=config["num_rows_high"],
            seq_len_per_gp=False,
            prior_type="mix_scm",
            n_jobs=-1,
        )


class MARNeuralNetwork(BaseMissingness):
    """
    Induces missingness based on a neural network with random weights.
    This is a simple implementation of the MAR missingness pattern.
    """

    def __init__(self, config: dict):
        self.mar_config = config["mar_config"]

    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        self.mar_config["N"] = X.shape[0]
        self.mar_config["T"] = X.shape[1]
        self.mar_config["row_neighbor_upper"] = X.shape[0] // 2
        self.mar_config["col_neighbor_upper"] = X.shape[1] // 2
        self.mar = MAR_missingness(self.mar_config)
        propensities = self.mar(X)
        mask = torch.bernoulli(propensities).bool()
        X[mask] = torch.nan
        return X


class MAROnesidedMissingness(BaseMissingness):
    """
    Induces missingness based on a neural network with random weights.
    This is a simple implementation of the MAR missingness pattern.
    """

    def __init__(self, config: dict):
        self.mar_onesided_config = config["mar_onesided_config"]

    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        self.mar_onesided_config["N"] = X.shape[0]
        self.mar_onesided_config["T"] = X.shape[1]
        self.mar_onesided_config["row_neighbor_upper"] = X.shape[0] // 2
        self.mar_onesided_config["col_neighbor_upper"] = X.shape[1] // 2
        self.mar_onesided_config["extreme_axis"] = "row"
        self.mar_onesided_config["extreme_neighbor_mode"] = "zero"
        self.mar = MAR_onesided_missingness(self.mar_onesided_config)
        propensities = self.mar(X)
        mask = torch.bernoulli(propensities).bool()
        X[mask] = torch.nan
        return X


class MARBlockNeuralNetwork(BaseMissingness):
    """
    Induces missingness based on a neural network with random weights.
    This is a simple implementation of the MAR missingness pattern.
    """

    def __init__(self, config: dict):
        self.mar_block_config = config["mar_block_config"]

    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        self.mar_block_config["N"] = X.shape[0]
        self.mar_block_config["T"] = X.shape[1]
        self.mar_block_config["row_blocks"] = X.shape[0] // 3
        self.mar_block_config["col_blocks"] = X.shape[1] // 3
        self.mar_block = MAR_block_missingness(self.mar_block_config)
        propensities, row_cumsum, col_cumsum = self.mar_block(X)

        def recover_block_missingness(propensity_small, row_cumsum, col_cumsum):
            N = row_cumsum[-1]
            T = col_cumsum[-1]
            missing_mask = torch.zeros(N, T)
            for i in range(row_cumsum.shape[0] - 1):
                for t in range(col_cumsum.shape[0] - 1):
                    missing_mask[
                        row_cumsum[i] : row_cumsum[i + 1],
                        col_cumsum[t] : col_cumsum[t + 1],
                    ] = torch.bernoulli(propensity_small[i, t])
            return missing_mask

        mask = recover_block_missingness(propensities, row_cumsum, col_cumsum).bool()
        X[mask] = torch.nan
        return X


class MARSequentialBandit(BaseMissingness):
    """
    Induces missingness based on a sequential bandit algorithm.
    This is a simple implementation of the MAR missingness pattern.
    """

    def __init__(self, config: dict):
        self.mar_sequential_bandit_config = config["mar_sequential_bandit_config"]

    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        self.mar_sequential_bandit_config["N"] = X.shape[0]
        self.mar_sequential_bandit_config["T"] = X.shape[1]
        self.mar_sequential_bandit = UnifiedBandit(self.mar_sequential_bandit_config)
        assignments, _, _ = self.mar_sequential_bandit.fit(X.detach().cpu().numpy())

        mask = torch.from_numpy(assignments.astype(bool)).to(X.device)
        X[mask] = torch.nan
        return X


class MARDiffusion(BaseMissingness):
    """MAR Diffusion missingness pattern generator using trained diffusion model"""

    def __init__(self, config: dict):
        super().__init__(config)
        self.device = torch.device(config.get("device", "cpu"))
        self.diffusion_config = mar_diffusion_config.copy()
        self.diffusion_config.update(config)

        # Model configuration
        model_config = {
            "n_channel": 1,
            "N": 2,
            "num_classes": 3,  # bandit, mar, block_mar
            "diffusion_steps": 1000,
            "hybrid_loss_coeff": 0.0,
        }

        # Initialize model
        self.model = MARDiffusionModel(model_config).to(self.device)

        # Load pretrained weights
        self._load_model_weights()

        # Set to evaluation mode
        self.model.eval()

    def _load_model_weights(self):
        """Load pre-trained model weights"""
        # Updated path to work from the new location
        weights_path = (
            Path(__file__).parent.parent
            / "diffusion"
            / "models"
            / "diffusion-row-10-30-col-10-30-mar0.3-marblock0.3-marbandit0.4-epoch100-bs32-samples30k-lr1e-3"
            / "model_final.pth"
        )

        if weights_path.exists():
            state_dict = torch.load(weights_path, map_location="cpu")
            try:
                self.model.x0_model.load_state_dict(state_dict, strict=True)
                print("Successfully loaded pretrained weights")
            except Exception as e:
                print(f"Warning: Could not load all weights: {e}")
                self.model.x0_model.load_state_dict(state_dict, strict=False)
                print("Loaded weights with partial matching")
        else:
            raise FileNotFoundError(f"Model weights not found at {weights_path}")

    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        """
        Generate missingness pattern using the diffusion model.

        Args:
            X: Input tensor of shape (height, width)

        Returns:
            Tensor with missing values (NaN) applied
        """
        height, width = X.shape

        # Use target_shape if specified, otherwise use X shape
        if self.diffusion_config["target_shape"] is not None:
            target_height, target_width = self.diffusion_config["target_shape"]
        else:
            target_height, target_width = height, width

        # Check if matrix size is within training range
        if not (10 <= target_height <= 30 and 10 <= target_width <= 30):
            warnings.warn(
                f"Matrix size ({target_height}, {target_width}) outside training range (10-30). "
                "Results may be suboptimal."
            )

        # Prepare X conditioning tensor
        X_cond = X.unsqueeze(0).unsqueeze(0)  # (1, 1, height, width)
        X_cond = X_cond.to(self.device)

        # Resize X_cond to target shape if needed
        if (target_height, target_width) != (height, width):
            X_cond = F.interpolate(
                X_cond,
                size=(target_height, target_width),
                mode="bilinear",
                align_corners=False,
            )

        # Generate missingness pattern
        with torch.no_grad():
            missingness_mask = self.model.generate(
                shape=(target_height, target_width),
                x_cond=X_cond,
                missingness_type=self.diffusion_config["missingness_type"],
                num_samples=self.diffusion_config["num_samples"],
            )

        # Convert to boolean mask and apply missingness
        mask = missingness_mask[0].bool()  # Remove batch dimension

        # If target shape differs from X shape, resize mask
        if (target_height, target_width) != (height, width):
            if self.diffusion_config["pad_mode"] == "pad_crop":
                # Simple crop/pad to match X shape
                if target_height >= height and target_width >= width:
                    mask = mask[:height, :width]
                else:
                    # Pad if target is smaller
                    pad_h = max(0, height - target_height)
                    pad_w = max(0, width - target_width)
                    mask = F.pad(mask, (0, pad_w, 0, pad_h))
                    mask = mask[:height, :width]
            else:  # tile mode
                # Tile the mask to cover X shape
                mask = mask.repeat(
                    height // target_height + 1, width // target_width + 1
                )[:height, :width]

        X_missing = X.clone()
        X_missing[mask] = torch.nan

        return X_missing


class MixedPattern(BaseMissingness):
    """
    Induces missingness by randomly selcting a type of missingness pattern and then inducing missingness based on that pattern.
    This randomness is controlled by the config parameters 'mcar_prob', 'mar_prob', and 'mnar_prob'.
    """
    def __init__(self, config: dict):
        self.patterns = [
            MCARPattern(config),
            # MARNeuralNetwork(config),
            MNARPattern(config),
            # MARSequentialBandit(config),
            # MARBlockNeuralNetwork(config),
            # MARPattern(config)
        ]
        self.pattern_names = [
            "mcar",
            # "mar_neural",
            "mnar",
            # "mar_sequential",
            # "mar_block",
            # "mar"
        ]
        self.weights = {
            "mcar": 0.8,
            "mnar": 0.2,
            # "mar": 1.0,
        }
        # self.probs = [1/len(self.patterns)] * len(self.patterns) # uniformly mix all patterns
        self.probs = [self.weights[pattern_name] for pattern_name in self.pattern_names]
        
        # check that the probabilities sum to 1
        if np.abs(sum(self.probs) - 1) > 1e-6:
            raise ValueError('The sum of the probabilities must be 1')
        
    def _induce_missingness(self, X: torch.Tensor) -> torch.Tensor:
        ind = np.random.choice(len(self.patterns), p=np.array(self.probs))
        pattern = self.patterns[ind]
        return pattern._induce_missingness(X)


# Main class
class MissingnessPrior(IterableDataset):
    """
    Main dataset class that provides an infinite iterator over synthetic tabular datasets.
    """

    generator_map = {
        "scm": SCMPriorTabICL,
        "latent_factor": LatentFactorPrior,
        "nonlinear_factor": NonLinearFactorPrior,
        "robust_pca": RobustPCAPrior,
    }
    missingness_map = {
        # Standard Patterns
        "mcar": MCARPattern,
        "mar": MARPattern,
        "mnar": MNARPattern,
        "mixed": MixedPattern,
        # Specific MNAR Patterns
        "mnar_rec_sys": MNARRecSysPattern,
        "mnar_panel": MNARPanelPattern,
        "mnar_sequential": MNARSequentialPattern,
        "mnar_polarization": MNARPolarizationPattern,
        "mnar_soft_polarization": MNARSoftPolarizationPattern,
        "mnar_latent_factor": MNARLatentFactorPattern,
        "mnar_positivity_violation": MNARPositivityViolationPattern,
        "mnar_user_cascade": MNARUserCascadePattern,
        "mnar_cluster_level": MNARClusterLevelPattern,
        "mnar_spatial_block": MNARSpatialBlockPattern,
        "mnar_censoring": MNARCensoringPattern,
        "mnar_two_phase_subset": MNARTwoPhaseSubsetPattern,
        "mnar_skip_logic": MNARSkipLogicPattern,
        "mnar_cold_start": MNARColdStartPattern,
        # MRI / matrix-completion benchmark: LORAKS Cartesian mask
        "loraks_cartesian": LoraksCartesianPattern,
        # Diffusion-based MAR pattern (lazy import to avoid circular dependency)
        "mar_diffusion": (
            lambda cfg: __import__(
                "mcpfn.diffusion", fromlist=["MARDiffusion"]
            ).MARDiffusion(cfg)
        ),
    }

    def __init__(
        self,
        generator_type: str = "scm",
        missingness_type: str = "mcar",
        config: dict = {},
        num_missing: int = 10,
        batch_size: int = 10,
        device: str = "cpu",
        verbose: bool = False,
        entry_wise_features: bool = True,
    ):
        self.config = config
        self.verbose = verbose
        self.batch_size = batch_size

        if generator_type not in self.generator_map:
            raise ValueError(
                f"Unknown generator type: {generator_type}. Available: {list(self.generator_map.keys())}"
            )
        if missingness_type not in self.missingness_map:
            raise ValueError(
                f"Unknown missingness type: {missingness_type}. Available: {list(self.missingness_map.keys())}"
            )

        self.generator = self.generator_map[generator_type](config)
        self.missingness_inducer = self.missingness_map[missingness_type](config)
        self.generator_type = generator_type
        self.missingness_type = missingness_type
        self.num_missing = num_missing
        self.device = device
        self.entry_wise_features = entry_wise_features

    @torch.no_grad()
    def get_batch(self, batch_size: Optional[int] = None):
        """Generates a new batch of datasets by combining a generator and a missingness pattern."""
        if batch_size is None:
            batch_size = self.batch_size
        X_list, y_list, train_sizes = (
            [],
            [],
            torch.zeros(self.batch_size, dtype=torch.long),
        )
        step = 0
        if self.verbose:
            pbar = tqdm(total=self.batch_size, desc="Generating batches")

        if isinstance(self.generator, SCMPriorTabICL):
            # X_list, y_list, train_sizes = self.generator.generate_batch(batch_size)
            scm_X, scm_y, _, _, _ = self.generator.scm.get_batch(batch_size)
        else:
            n_rows = np.random.randint(self.config["num_rows_low"], self.config["num_rows_high"]+1)
            n_cols = np.random.randint(self.config["num_cols_low"], self.config["num_cols_high"]+1)
            new_config = copy.deepcopy(self.config)
            new_config["num_rows_low"] = n_rows
            new_config["num_rows_high"] = n_rows
            new_config["num_cols_low"] = n_cols
            new_config["num_cols_high"] = n_cols
            new_config["latent_rank_high"] = min(
                new_config["latent_rank_high"], n_rows, n_cols
            )  # Ensure rank is not too high

            self.generator = self.generator_map[self.generator_type](new_config)
            
        pattern_weights = []
        while step < self.batch_size:
            # for i in tqdm(range(self.batch_size), desc="Generating batches"):
            # try:
            if isinstance(self.generator, SCMPriorTabICL):
                X = torch.cat(
                    (scm_X[step, :, :], scm_y[step, :].unsqueeze(dim=-1)), dim=1
                )
            else:
                complete_df = self.generator.generate_complete_matrix()
                X = torch.tensor(complete_df.values, dtype=torch.float32)

            if X.numel() == 0:  # if the matrix is empty, skip
                continue
            X = normalize_data(X.clone())
            X_missing = self.missingness_inducer._induce_missingness(X.clone())
            # pattern_weights.append(self.missingness_inducer.weights[pattern_name])
            pattern_weights.append(1.0)
            # Normalize the data after missingness is induced
            # Use mean and std from observed values only
            X_missing_normalized, (mean, std) = normalize_data(
                torch.unsqueeze(X_missing, 1), return_scaling=True
            )
            X_missing = torch.squeeze(X_missing_normalized, 1)
            X = torch.squeeze(normalize_data(torch.unsqueeze(X, 1), mean=mean, std=std), 1)
            
            
            if self.entry_wise_features:
                train_X, train_y, test_X, test_y = create_train_test_sets(
                    X_missing, X_full=X
                )
                # if train_X.shape[0] != train_X.shape[0] + test_X.shape[0] - self.num_missing:
                #     raise ValueError('train_sizes[i] != train_X.shape[0] + test_X.shape[0] - self.num_missing')
                X_list.append(torch.cat((train_X, test_X)))
                y_list.append(torch.cat((train_y, test_y)))
                train_sizes[step] = train_X.shape[0]
            else:
                X_list.append(X_missing)
                y_list.append(X)
                train_sizes[step] = X.shape[0]
            step += 1
            if self.verbose:
                pbar.update(1)
            # except Exception as e: # Skip if any error occurs
            #     print(e)
            #     continue
        if not X_list:
            return self.get_batch()  # Retry if all generations failed

        X_full = torch.stack(X_list, dim=0)
        y_full = torch.stack(y_list, dim=0)

        # d is the number of columns. This should always be the same across datasets.
        d = torch.tensor(X_list[0].shape[1], device=self.device).repeat(len(X_list))
        seq_lens = torch.tensor(
            [len(y) for y in y_list], device=self.device, dtype=torch.long
        )
        # train sizes is the part that is different
        return (X_full, y_full, d, seq_lens, train_sizes), torch.tensor(pattern_weights, device=self.device)

    def __iter__(self) -> "MissingnessPrior":
        """
        Returns an iterator that yields batches indefinitely.

        Returns
        -------
        self
            Returns self as an iterator
        """
        return self

    def __next__(self) -> Tuple[Tensor, Tensor, Tensor, Tensor, Tensor]:
        """
        Returns the next batch from the iterator. Since this is an infinite
        iterator, it never raises StopIteration and instead continuously generates
        new synthetic data batches.
        """
        # with DisablePrinting():
        return self.get_batch()


# Execution Block
if __name__ == "__main__":
    config = {
        "num_rows_low": 5,
        "num_rows_high": 5.5,
        "num_cols_low": 5,
        "num_cols_high": 5.5,
        "p_missing": 0.4,
        # SCM configs
        "num_nodes_low": 60,
        "num_nodes_high": 80,
        "graph_generation_method": ["MLP-Dropout", "Scale-Free"],
        "root_node_noise_dist": ["Normal", "Uniform"],
        "scm_activation_functions": list(ACTIVATION_FUNCTIONS.keys()),
        "xgb_n_estimators_exp_scale": 0.5,
        "xgb_max_depth_exp_scale": 0.5,
        "apply_feature_warping_prob": 0.0,
        "apply_quantization_prob": 0.0,
        # MNAR configs
        "threshold_quantile": 0.25,
        "n_core_items": 5,
        "n_genres": 3,
        "n_policies": 4,
        # Latent Factor configs
        "latent_rank_low": 1,
        "latent_rank_high": 3,
        "latent_spike_p": 0.3,
        "latent_slab_sigma": 2.0,
        # Non-linear Factor configs
        "spline_knot_k": [3, 5, 7],
        "gp_length_scale_low": 0.3,
        "gp_length_scale_high": 2.0,
        "fourier_dim_low": 100,
        "fourier_dim_high": 501,
        # Robust-PCA configs
        "rpca_beta_a": 2,
        "rpca_beta_b": 30,
        # Soft Polarization configs
        "soft_polarization_alpha": 2.5,
        "soft_polarization_epsilon": 0.05,
        # User Cascade configs
        "cascade_n_genres": 5,
        "cascade_delta": 1.5,
        # Cluster Level configs
        "cluster_level_n_row_clusters": 8,
        "cluster_level_n_col_clusters": 8,
        "cluster_level_tau_r_std": 1.0,
        # Spatial Block configs
        "spatial_block_n_blocks": 5,
        "spatial_block_p_geom": 0.2,
        # Last few ones
        "censor_quantile": 0.1,
        "two_phase_cheap_fraction": 0.4,
        "two_phase_beta": 2.5,
        "skip_logic_p_noise": 0.9,
        "cold_start_fraction": 0.3,
        "cold_start_gamma": 0.15,
    }

    # Example, specify one data generation type and one missingness pattern
    prior = MissingnessPrior(
        generator_type="latent_factor",
        missingness_type="mcar",
        num_missing=10,
        config=config,
        batch_size=1,
        verbose=False,
        entry_wise_features=False,
    )

    (X_full, y_full, d, seq_lens, train_sizes), _ = prior.get_batch()
    
    print(X_full.shape, y_full.shape, d.shape, seq_lens.shape, train_sizes.shape)
    
    print(X_full)
    print(y_full)
